### ISSUE TITLE
多标签实现

### ISSUE THREAD

**Issue by eliohn** [sanwer/Browser#2]
这个DEMO里有一个问题，能不能帮解答一下。
这个在页面新开的窗口OnBeforePopup 创建出来的窗口都新开链接里面都没有带来路。
这样实现多标签好像不行。

**Comment by sanwer** [comment]
这个是一个小项目的演示程序，无需开标签，没有进一步研究，后续维护可能性小。
有啥问题请自行解决，抱歉。
